terran_units = {
    'TerranInfantryWeaponsLevel1': {},
    'TerranInfantryWeaponsLevel2': {},
    'TerranInfantryWeaponsLevel3': {},
    'TerranInfantryArmorsLevel1': {},
    'TerranInfantryArmorsLevel2': {},
    'TerranInfantryArmorsLevel3': {},
    'PersonalCloaking': {},
    'TerranVehicleWeaponsLevel1': {},
    'TerranVehicleWeaponsLevel2': {},
    'TerranVehicleWeaponsLevel3': {},
    'TerranVehicleAndShipArmorsLevel1': {},
    'TerranVehicleAndShipArmorsLevel2': {},
    'TerranVehicleAndShipArmorsLevel3': {},
    'DrillClaws': {},
    'LiberatorAGRangeUpgrade': {},
    'TerranShipWeaponsLevel1': {},
    'TerranShipWeaponsLevel2': {},
    'TerranShipWeaponsLevel3': {},
    'BansheeCloak': {},
    'BansheeSpeed': {},
    'RavenCorvidReactor': {},
    'RavenDamageUpgrade': {},
    'BattlecruiserEnableSpecializations': {},
    'BattlecruiserBehemothReactor': {},
    'HighCapacityBarrels': {},
    'CycloneLockOnDamageUpgrade': {},
    'MedivacIncreaseSpeedBoost': {},
    'Stimpack': {},
    'ShieldWall': {},
    'PunisherGrenades': {},
    'TerranBuildingArmor': {},
    'NeosteelFrame': {},
    'HiSecAutoTracking': {},
    'Ghost': {},
    'Nuke': {},
    'MULE': {},
    'WidowMine': {},
    'Liberator': {},
    'Banshee': {},
    'Raven': {},
    'Battlecruiser': {},
    'Thor': {},
    'SiegeTank': {},
    'VikingAssault': {},
    'Reaper': {},
    'VikingFighter': {},
    'Hellion': {},
    'Cyclone': {},
    'Medivac': {},
    # 'SCV': {},
    'Marine': {},
    'BattleHellion': {},
    'Marauder': {},
    'GhostAcademy': {},
    'FusionCore': {},
    'FactoryTechLab': {},
    'FactoryReactor': {},
    'StarportTechLab': {},
    'BarracksTechLab': {},
    'SensorTower': {},
    'Factory': {},
    'Refinery': {},
    'Starport': {},
    # 'SupplyDepot': {},
    'StarportReactor': {},
    'CommandCenter': {},
    'Bunker': {},
    'EngineeringBay': {},
    'OrbitalCommand': {},
    'Barracks': {},
    'Armory': {},
    'MissileTurret': {},
    'BarracksReactor': {},
    'PlanetaryFortress': {},
}

zerg_units = {
    'ZergMeleeWeaponsLevel1': {},
    'ZergMeleeWeaponsLevel2': {},
    'ZergMeleeWeaponsLevel3': {},
    'ZergGroundArmorsLevel1': {},
    'ZergGroundArmorsLevel2': {},
    'ZergGroundArmorsLevel3': {},
    'Burrow': {},
    'CentrificalHooks': {},
    'zerglingattackspeed': {},
    'zerglingmovementspeed': {},
    'ZergFlyerWeaponsLevel1': {},
    'ZergFlyerWeaponsLevel2': {},
    'ZergFlyerWeaponsLevel3': {},
    'ZergFlyerArmorsLevel1': {},
    'ZergFlyerArmorsLevel2': {},
    'ZergFlyerArmorsLevel3': {},
    'ZergMissileWeaponsLevel1': {},
    'ZergMissileWeaponsLevel2': {},
    'ZergMissileWeaponsLevel3': {},
    'hydraliskspeed': {},
    'InfestorEnergyUpgrade': {},
    'NeuralParasite': {},
    'ChitinousPlating': {},
    'overlordspeed': {},
    'GlialReconstitution': {},
    'TunnelingClaws': {},
    'Baneling': {},
    'NydusWorm': {},
    'Zergling': {},
    'SwarmHost': {},
    'Mutalisk': {},
    'Hydralisk': {},
    'Queen': {},
    'Infestor': {},
    'Corruptor': {},
    'NydusCanal': {},
    # 'Drone': {},
    'Ultralisk': {},
    'Viper': {},
    'Ravager': {},
    'Overseer': {},
    'LurkerMP': {},
    'Roach': {},
    # 'Overlord': {},
    'BroodLord': {},
    'Extractor': {},
    'UltraliskCavern': {},
    'SpineCrawler': {},
    'Lair': {},
    # 'Larva': {},
    'LurkerDenMP': {},
    'SporeCrawler': {},
    'BanelingNest': {},
    'EvolutionChamber': {},
    'Spire': {},
    'RoachWarren': {},
    'Hive': {},
    'Hatchery': {},
    'InfestationPit': {},
    'GreaterSpire': {},
    'NydusNetwork': {},
    'SpawningPool': {},
    'HydraliskDen': {},
}

protoss_units = {
    'ProtossGroundWeaponsLevel1': {},
    'ProtossGroundWeaponsLevel2': {},
    'ProtossGroundWeaponsLevel3': {},
    'ProtossGroundArmorsLevel1': {},
    'ProtossGroundArmorsLevel2': {},
    'ProtossGroundArmorsLevel3': {},
    'ProtossShieldsLevel1': {},
    'ProtossShieldsLevel2': {},
    'ProtossShieldsLevel3': {},
    'ProtossAirWeaponsLevel1': {},
    'ProtossAirWeaponsLevel2': {},
    'ProtossAirWeaponsLevel3': {},
    'ProtossAirArmorsLevel1': {},
    'ProtossAirArmorsLevel2': {},
    'ProtossAirArmorsLevel3': {},
    'PhoenixRangeUpgrade': {},
    'ObserverGraviticBooster': {},
    'ExtendedThermalLance': {},
    'PsiStormTech': {},
    'AdeptPiercingAttack': {},
    'Charge': {},
    'GraviticDrive': {},
    'BlinkTech': {},
    'CarrierLaunchSpeedUpgrade': {},
    'WarpGateResearch': {},
    'DarkTemplar': {},
    'Phoenix': {},
    'Sentry': {},
    'Observer': {},
    'Colossus': {},
    'Disruptor': {},
    'MothershipCore': {},
    'Mothership': {},
    # 'Probe': {},
    'Immortal': {},
    'HighTemplar': {},
    'Adept': {},
    'Zealot': {},
    'WarpPrism': {},
    'Stalker': {},
    'Oracle': {},
    'Tempest': {},
    'Archon': {},
    'Carrier': {},
    'Interceptor': {},
    'VoidRay': {},
    'TwilightCouncil': {},
    'TemplarArchive': {},
    'RoboticsFacility': {},
    'CyberneticsCore': {},
    'PhotonCannon': {},
    'RoboticsBay': {},
    'WarpGate': {},
    'Stargate': {},
    'Forge': {},
    'Assimilator': {},
    'DarkShrine': {},
    'Nexus': {},
    'FleetBeacon': {},
    # 'Pylon': {},
    'Gateway': {},
}

ignore_killed = [
    'AdeptPhaseShift'
]

workers = [
    'Probe', 'SCV', 'Drone', 'MULE'
]

irrelevant_units = [
    'Pylon', 'Overlord', 'SupplyDepot'
]

races = {
    'Protoss': protoss_units,
    'Terran': terran_units,
    'Zerg': zerg_units
}

for units in races.itervalues():
    index = 0
    for unit in units.itervalues():
        unit['id'] = index
        index += 1
